### ISSUE TITLE
build-and-publish-docker-image jobs use  deprecated version of docker/build-push-action (v1)

### ISSUE THREAD

**Issue by herveleclerc** [microsoft/MCW-Cloud-native-applications#192]
docker/build-push-action@v1 is deprecated 

upgrade to v2.

old block

```
build-and-publish-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
    # Checkout the repo
    - uses: actions/checkout@master

    - name: Build and push an image to container registry
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        path: ${{ env.dockerfilePath  }}
        dockerfile: '${{ env.dockerfilePath }}/Dockerfile'
        registry: ${{ env.containerRegistry }}
        repository: ${{ env.imageRepository }}
        tags: ${{ env.tag }},latest
```

Should change to something like :

```
  build-and-publish-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.containerRegistry }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push an image to container registry
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.dockerfilePath  }}
          file: "${{ env.dockerfilePath }}/Dockerfile"
          pull: true
          push: true
          tags: |
            ${{ env.containerRegistry }}/${{ env.imageRepository }}:${{ env.tag }}
            ${{ env.containerRegistry }}/${{ env.imageRepository }}:latest
```
